### ISSUE TITLE
Implementation won't work in a multi-threaded environment

### ISSUE THREAD

**Issue by goutkannan** [buckyroberts/Python-Design-Patterns#3]
Hi, 

The implementation of Python-Design-Patterns/04_singleton/main.py assumes the target to be a single threaded. In a multi-threaded scenario, there needs to be lock while creating the instance. Thread safe and a non lock version can be found here https://stackoverflow.com/questions/6760685/creating-a-singleton-in-python.

**Comment by nabinkhadka** [comment]
As far as I know, this repo is here just for teaching purpose and hence it is kept as simple as possible. No need to be fancy.

**Comment by goutkannan** [comment]
OK. I can contribute the thread safe version, it might help..!!
